export const sample_foods = [
    {
        id: '1',
        name: 'samosa',
        cookTime: '5-10',
        price: 5,
        favourite: true,
        origins: ['India'],
        stars: 5,
        imageUrl: 'food-1.jpg',
        tags: ['Breakfast', 'Fastfood'],
    },
    {
        id: '2',
        name: 'kachori',
        cookTime: '5-10',
        price: 3,
        favourite: false,
        origins: ['India'],
        stars: 4,
        imageUrl: 'food-2.jpg',
        tags: ['Breakfast', 'Fastfood'],
    },
    {
        id: '3',
        name: 'breadpakoda',
        cookTime: '5-10',
        price: 15,
        favourite: false,
        origins: ['India'],
        stars: 2,
        imageUrl: 'food-3.jpg',
        tags: ['Breakfast', 'Fastfood'],
    },
    {
        id: '4',
        name: 'tea',
        cookTime: '5-10',
        price: 10,
        favourite: true,
        origins: ['India'],
        stars: 4.5,
        imageUrl: 'food-4.jpg',
        tags: ['Breakfast', 'Fastfood'],
    },
    {
        id: '5',
        name: 'coffee',
        cookTime: '5-10',
        price: 20,
        favourite: true,
        origins: ['India', 'England'],
        stars: 3.5,
        imageUrl: 'food-5.jpg',
        tags: ['Breakfast', 'Fastfood'],
    },
    {
        id: '6',
        name: 'chowmwin',
        cookTime: '10-20',
        price: 25,
        favourite: false,
        origins: ['India','China'],
        stars: 3,
        imageUrl: 'food-6.jpg',
        tags: ['Breakfast', 'Fastfood'],
    },
];